export const USERS_MESSAGE = {
  GET_OPTIONS_FAILED: '获取下拉列表失败!',
  GET_USERS_FAILED: '获取用户列表失败!',
  USERNAME_REQUIRED: '用户名必填',
  PASSWORD_REQUIRED: '密码必填',
  CONFIRM_PASSWORD_REQUIRED: '确认密码必填',
  PASSWORD_DIFFERENT: '两次输入的密码不同',
  OLD_PASSWORD_REQUIRED: '密码必填',
  NEW_PASSWORD_REQUIRED: '新密码必填',
  NEW_CONFIRM_PASSWORD_REQUIRED: '新确认密码必填',
  PHONE_INVALID: '手机号码格式不正确',
  EMAIL_INVALID: '电子邮件格式不正确',
  CREATE_SUCCEED: '创建用户成功!',
  CREATE_FAILED: '创建用户失败!',
  UPDATE_SUCCEED: '修改用户成功!',
  UPDATE_FAILED: '修改用户失败!',
  DELETE_CONFIRM: '确定删除该用户吗?',
  DELETE_SUCCEED: '删除用户成功!',
  DELETE_FAILED: '删除用户失败!',
  CHANGE_PASSWORD_SUCCEED: '修改密码成功!',
  CHANGE_PASSWORD_FAILED: '修改密码失败!',
};
